

## auth
// note: should use GET for refresh, signup but easier for testing

### login
POST /auth/login
content-type: application/json
ex.
POST /auth/login
-- content
{
    "email": "test@example.com",
    "password": "motdepasse"
}

### signup
POST /auth/signup
content-type: none
authorization: Bearer
ex.


### refresh token
POST /auth/refresh
content-type: none
cookie(ssl): refreshToken
ex.
POST /auth/refresh
content:
sslcookie: "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE3YWE4MmY3MWY0ZmZjNTA5ZWJlOWUiLCJlbWFpbCI6Ik5heWxhX0JlcnNldEBob3RtYWlsLmNvbSIsIm5hbWUiOiJFbnlhIFJvY2hhdCIsImlhdCI6MTc0NjUyMjY1OCwiZXhwIjoxNzQ2NTIyNzE4fQ.ADiaWaneJXmVkOshgoEfYLfHDbv90qXqHCX-MiVbEKU"



## jobs

### get info about one specific user with id
GET /job/:id
content-type: none
Authorization: Bearer {{token}}
ex.
GET /job/680b8b4b9b74a568594c1502

### create a new job
POST /job/
content-type: application/json
ex.
POST /job/
-- content
{
    "jobTitle": "test pas encore modifié",
    "language": "FR",
    "link": "https://example.com",
    "source": "linkedin"
}

### modify a job
PUT /job/
content-type: application/json
Authorization: Bearer {{token}}
ex.
PUT /job/
-- content
{
    "_id": "680b8b4b9b74a568594c1502",
    "jobTitle": "test modifié une fois",
    "language": "FR",
    "link": "https://example.com",
    "source": "linkedin"
}

### delete a job
DELETE /job/:id
content-type: none
Authorization: Bearer {{token}}
ex.
DELETE /job/:680b8b4b9b74a568594c1502



